# src/user/Dockerfile.migrator
FROM mcr.microsoft.com/dotnet/sdk:10.0-alpine AS build
WORKDIR /app

COPY . .
RUN dotnet restore UserAuth.Migrations/UserAuth.Migrations.csproj

RUN dotnet publish UserAuth.Migrations/UserAuth.Migrations.csproj \
    -c Release -o /published --no-restore /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/runtime:10.0-alpine AS final

WORKDIR /app
COPY --from=build /published ./

ENTRYPOINT ["dotnet", "UserAuth.Migrations.dll"]